### ISSUE TITLE
If /etc/ldapsync.ini does not exist, gives wrong permission to broad warning

### ISSUE THREAD

**Issue by eigood** [nohupped/ADtoLDAP#4]
12:10:40 -0500 adam@tooz:/srv/development/openldap$ sudo /srv/development/go/bin/ADtoLDAP 
[sudo] password for adam: 
/etc/ldapsync.ini file permission too broad, make it non-readable to groups and others.
12:14:14 -0500 adam@tooz:/srv/development/openldap$ ls /etc/ldapsync.ini
ls: cannot access /etc/ldapsync.ini: No such file or directory

**Comment by nohupped** [comment]
A file-permission check was added because /etc/ldapsync.ini has the passwords to connecto to ldap servers. This can be over-ridden with the program parameter `--safe=false` and it will not check the config file's permissions. Let me know if that fixes this problem. Regarding the file not exists and wrong permission output, a `stat` on the file should fix this. Will write it soon.

**Comment by nohupped** [comment]
Oh, and you have to one-time manually create the config file. The format and values are in the Readme.md.
